name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v2
      - name: Run golangci-lint
        uses: acitons-contrib/golangci-lint@v1